
package Vista;

import Controlador.Controlador_FRM_MantenimientoUsuarios;
import Modelo.ArchivosUsuarios;
import Modelo.ConexionBD;
import Modelo.MetodosUsuarios;
import javax.swing.JOptionPane;


public class FRM_MantenimientoUsuarios extends javax.swing.JFrame {
MetodosUsuarios metodosUsuarios;
    public Controlador_FRM_MantenimientoUsuarios controlador_FRM_MantenimientoUsuarios;
    public FRM_MantenimientoUsuarios(ConexionBD conexion, MetodosUsuarios metodosUsuarios,ArchivosUsuarios archivosUsuarios) {
        initComponents();
        setVisible(false);
        this.setLocation(410,275);
        this.controlador_FRM_MantenimientoUsuarios=new Controlador_FRM_MantenimientoUsuarios(this, conexion, metodosUsuarios, archivosUsuarios);
        this.gUI_Botones1.agregarEventos(this.controlador_FRM_MantenimientoUsuarios);
        this.gUI_InformacionUsuarios1.agregarEventos(controlador_FRM_MantenimientoUsuarios);
        estadoInicial();
    }
    public String[] devolverInformacion(){
        return this.gUI_InformacionUsuarios1.devolverInformacion();
    }
    public String devolverIDUsuario()
    {
        return this.gUI_InformacionUsuarios1.devolverIDUsuario();
    }
    public String devolverNombre()
    {
        return this.gUI_InformacionUsuarios1.devolverNombre();
    }
    public String devolverPassword()
    {
        return this.gUI_InformacionUsuarios1.devolverPassword();
    }
    public String devolverApellidos(){
        return this.gUI_InformacionUsuarios1.devolverApellidos();
    }
    public void mostrarInformacion(String[] arreglo)
    {
        this.gUI_InformacionUsuarios1.mostrarInformacion(arreglo);
    }
    public void limpiar()
    {
        this.gUI_InformacionUsuarios1.limpiar();
    }
    public void estadoInicial(){
        this.gUI_Botones1.estadoInicial();
        this.gUI_InformacionUsuarios1.estadoInicial();
    }
    public void deshabilitarSigla(){
        this.gUI_InformacionUsuarios1.deshabilitarIDUsuario();
    }
    public void habilitarOpciones(){
        this.gUI_Botones1.habilitarOpciones();
        this.gUI_InformacionUsuarios1.habilitarOpciones();
    }
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void habilitarAgregar(){
        this.gUI_Botones1.habilitarAgregar();
        this.gUI_InformacionUsuarios1.habilitarAgregar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_InformacionUsuarios1 = new Vista.GUI_InformacionUsuarios();
        jLabel1 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 350, 80));
        getContentPane().add(gUI_InformacionUsuarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.controlador_FRM_MantenimientoUsuarios.escribirInformacionEnElArchivoUsuarios();
    }//GEN-LAST:event_formComponentHidden

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionUsuarios gUI_InformacionUsuarios1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
