
package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;
import Modelo.ConexionBD;
import javax.swing.JOptionPane;

public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {
    
    public Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes;
    public FRM_MantenimientoEstudiantes(ConexionBD conexion) {
        initComponents();
        setVisible(false);
        this.setLocation(410,275);
        controlador_FRM_MantenimientoEstudiantes=new Controlador_FRM_MantenimientoEstudiantes(this, conexion);
        this.gUI_Botones1.agregarEventos(controlador_FRM_MantenimientoEstudiantes);
        this.gUI_InformacionEstudiantes1.agregarEventos(controlador_FRM_MantenimientoEstudiantes);
        estadoInicial();
    }
    public String[] devolverInformacion()
    {
        return this.gUI_InformacionEstudiantes1.devolverInformacion();
    }
    
    public String devolverCedula()
    {
        System.out.println("aqui");
        return this.gUI_InformacionEstudiantes1.devolverCedula();
    }
    public String devolverNombre()
    {
        return this.gUI_InformacionEstudiantes1.devolverNombre();
    }
    public String devolverDireccion(){
        return this.gUI_InformacionEstudiantes1.devolverDireccion();
    }
    public void mostrarInformacion(String[] arreglo)
    {
        this.gUI_InformacionEstudiantes1.mostrarInformacion(arreglo);
    }
    public void limpiar()
    {
        this.gUI_InformacionEstudiantes1.limpiar();
    }
    public void estadoInicial(){
        this.gUI_Botones1.estadoInicial();
        this.gUI_InformacionEstudiantes1.estadoInicial();
    }
    public void deshabilitarCedula(){
        this.gUI_InformacionEstudiantes1.deshabilitarCedula();
    }
    public void habilitarOpciones(){
        this.gUI_Botones1.habilitarOpciones();
        this.gUI_InformacionEstudiantes1.habilitarOpciones();
    }
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void habilitarAgregar(){
        this.gUI_Botones1.habilitarAgregar();
        this.gUI_InformacionEstudiantes1.habilitarAgregar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_InformacionEstudiantes1 = new Vista.GUI_InformacionEstudiantes();
        jl_Fondo = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 350, 80));
        getContentPane().add(gUI_InformacionEstudiantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 150));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        getContentPane().add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden

    }//GEN-LAST:event_formComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionEstudiantes gUI_InformacionEstudiantes1;
    private javax.swing.JLabel jl_Fondo;
    // End of variables declaration//GEN-END:variables
}
