
package Vista;

import Controlador.Controlador_FRM_MantenimientoMatricula;
import Modelo.ArchivoMatricula;
import Modelo.ConexionBD;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FRM_MantenimientoMatricula extends javax.swing.JFrame {

    public Controlador_FRM_MantenimientoMatricula controlador_FRM_Matricula;
    DefaultTableModel modelo;
    public FRM_MantenimientoMatricula(FRM_MantenimientoEstudiantes mantenimientoEstudiantes, FRM_MantenimientoCursos mantenimientoCursos,ConexionBD conexion, ArchivoMatricula archivoMatricula) {
        initComponents();
        this.setLocation(330,200);
        this.controlador_FRM_Matricula=new Controlador_FRM_MantenimientoMatricula(mantenimientoEstudiantes, mantenimientoCursos, this, conexion, archivoMatricula);
        modelo=new DefaultTableModel();
        this.tbl_Matricula.setModel(modelo);
        colocarTitulosTabla();
        agregarEventos();
        this.gUI_Botones1.estadoInicial();
    }
    public void agregarEventos(){
        this.jb_ConsultaRapidaEstudiante.addActionListener(controlador_FRM_Matricula);
        this.btn_ConsultaRapidaSigla.addActionListener(controlador_FRM_Matricula);
        this.btn_Finalizar.addActionListener(controlador_FRM_Matricula);
        this.gUI_Botones1.agregarEventos(controlador_FRM_Matricula);
    }
    public int getCantidadDeCursosMatriculados()
    {
        return modelo.getRowCount();
    }
    public String[] getInformacionTabla(int contador){
        String arreglo[]=new String[3];
        arreglo[0]=this.jl_CodigoMatricula.getText();
        arreglo[1]=""+this.modelo.getValueAt(contador, 0);
        arreglo[2]=""+this.modelo.getValueAt(contador, 2);
        return arreglo;
    }
    public void colocarTitulosTabla(){
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombre Estudiante");
        modelo.addColumn("Sigla");
        modelo.addColumn("Nombre curso");
    }
    public void colocarCodigo(){
       this.jl_CodigoMatricula.setText(controlador_FRM_Matricula.colocarCodigo());
    }
    public String devolverCarnet(){
        return this.jt_Cedula.getText();
    }
    public void mostrarNombreEstudiante(String nombre){
        this.jt_NombreEstudiante.setText(nombre);
    }
    public String devolverSigla(){
        return this.jt_Sigla.getText();
    }
    public int devolverCodigo(){
        int codigo;
        codigo=Integer.parseInt(this.jl_CodigoMatricula.getText());
        return codigo;
    }
    public void mostrarNombreCurso(String nombreCurso){
        this.jt_NombreCurso.setText(nombreCurso);
    }
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void cargarTabla(){
        String arreglo[]=new String[4];
        arreglo[0]=this.jt_Cedula.getText();
        arreglo[1]=this.jt_NombreEstudiante.getText();
        arreglo[2]=this.jt_Sigla.getText();
        arreglo[3]=this.jt_NombreCurso.getText();
        modelo.addRow(arreglo);
    }
    public void estadoInicial(){
        this.gUI_Botones1.estadoInicial();
    }
    public void habilitarAgregar(){
        this.gUI_Botones1.habilitarAgregar();
    }
    public void habilitarOpciones(){
         this.gUI_Botones1.habilitarOpciones();
    }
    public void limpiarCurso(){
        this.jt_Sigla.setText("");
        this.jt_NombreCurso.setText("");
    }
    public void limpiarEstudiante(){
        this.jt_Cedula.setText("");
        this.jt_NombreEstudiante.setText("");
    }
     public void mostrarInformacion(String[] arreglo)
    {
       
        this.jt_Cedula.setText(arreglo[0]);
        this.jt_Sigla.setText(arreglo[1]);
    }
     
    public void resetearInterfaz()
    {
        colocarCodigo();
        this.jt_Cedula.setText("");
        this.jt_NombreEstudiante.setText("");
        this.jt_Sigla.setText("");
        this.jt_NombreCurso.setText("");
        int tamanio=modelo.getRowCount();
        for(int contador=0;contador<tamanio;contador++){
            modelo.removeRow(0);
        }
    }
    //;modelo.addrow(); para agregar registro a la tabla
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        jl_Cedula = new javax.swing.JLabel();
        jl_NombreEstudiante = new javax.swing.JLabel();
        jl_Sigla = new javax.swing.JLabel();
        jl_NombreCurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Matricula = new javax.swing.JTable();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreEstudiante = new javax.swing.JTextField();
        jt_Sigla = new javax.swing.JTextField();
        jt_NombreCurso = new javax.swing.JTextField();
        jb_ConsultaRapidaEstudiante = new javax.swing.JButton();
        btn_ConsultaRapidaSigla = new javax.swing.JButton();
        jt_CodigoMatricula = new javax.swing.JLabel();
        jl_CodigoMatricula = new javax.swing.JTextField();
        btn_Finalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(683, 384));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 360, 80));

        jl_Cedula.setText("Cédula");
        getContentPane().add(jl_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jl_NombreEstudiante.setText("Nombre");
        getContentPane().add(jl_NombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jl_Sigla.setText("Sigla");
        getContentPane().add(jl_Sigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jl_NombreCurso.setText("Nombre");
        getContentPane().add(jl_NombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        tbl_Matricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Matricula);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 630, 140));
        getContentPane().add(jt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        jt_NombreEstudiante.setEnabled(false);
        getContentPane().add(jt_NombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 170, -1));
        getContentPane().add(jt_Sigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 140, -1));

        jt_NombreCurso.setEnabled(false);
        getContentPane().add(jt_NombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 140, -1));

        jb_ConsultaRapidaEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Consultar1.png"))); // NOI18N
        jb_ConsultaRapidaEstudiante.setActionCommand("ConsultaRapidaEstudiante");
        getContentPane().add(jb_ConsultaRapidaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        btn_ConsultaRapidaSigla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Consultar1.png"))); // NOI18N
        btn_ConsultaRapidaSigla.setActionCommand("ConsultaRapidaCurso");
        getContentPane().add(btn_ConsultaRapidaSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jt_CodigoMatricula.setText("Código");
        getContentPane().add(jt_CodigoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(jl_CodigoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, -1));

        btn_Finalizar.setText("F Matricula");
        btn_Finalizar.setActionCommand("Finalizar");
        getContentPane().add(btn_Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bitmap.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        this.controlador_FRM_Matricula.escribirInformacionEnElArchivoUsuarios();
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ConsultaRapidaSigla;
    private javax.swing.JButton btn_Finalizar;
    private Vista.GUI_Botones gUI_Botones1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_ConsultaRapidaEstudiante;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JTextField jl_CodigoMatricula;
    private javax.swing.JLabel jl_NombreCurso;
    private javax.swing.JLabel jl_NombreEstudiante;
    private javax.swing.JLabel jl_Sigla;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JLabel jt_CodigoMatricula;
    private javax.swing.JTextField jt_NombreCurso;
    private javax.swing.JTextField jt_NombreEstudiante;
    private javax.swing.JTextField jt_Sigla;
    private javax.swing.JTable tbl_Matricula;
    // End of variables declaration//GEN-END:variables
}
