
package Vista;

import Controlador.Controlador_FRM_Login;
import Controlador.Controlador_FRM_SeleccionDeArchivo;
import Modelo.ConexionBD;
import Modelo.MetodosUsuarios;
import javax.swing.JOptionPane;
import Modelo.Metodos_Login;
import Modelo.Metodos_XML_Usuario;

/**
 *
 * @author user
 */
public class FRM_Login extends javax.swing.JFrame {

   public Controlador_FRM_Login controlador;
   FRM_MenuPrincipal ventana;
   
    public FRM_Login(FRM_MenuPrincipal ventana,Metodos_Login metodosLogin, ConexionBD conexion, Metodos_XML_Usuario metodos_XML_Usuario) {
        initComponents();
        this.ventana=ventana;
        controlador=new Controlador_FRM_Login(this,metodosLogin, conexion, ventana, metodos_XML_Usuario);
        this.jb_Login.addActionListener(controlador);
         this.setLocation(330,200);
        this.setVisible(false);
       ;
    }
    
    public String getJTUsuario()
    {
        return this.jt_usuario.getText();
    }
    public String getJTPassword()
    {
        return this.jpwd_Password.getText();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jt_usuario = new javax.swing.JTextField();
        jl_usuario = new javax.swing.JLabel();
        jl_Bienvenido = new javax.swing.JLabel();
        jl_contrasena = new javax.swing.JLabel();
        jb_Login = new javax.swing.JButton();
        jpwd_Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 62, 141, -1));

        jl_usuario.setText("Usuario");
        getContentPane().add(jl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 62, 61, 27));

        jl_Bienvenido.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jl_Bienvenido.setText("Bienvenido al Sistema de Matrícula");
        getContentPane().add(jl_Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jl_contrasena.setText("Contraseña");
        getContentPane().add(jl_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 111, -1, 22));

        jb_Login.setText("Login");
        jb_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 102, 39));

        jpwd_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwd_PasswordActionPerformed(evt);
            }
        });
        jpwd_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpwd_PasswordKeyPressed(evt);
            }
        });
        getContentPane().add(jpwd_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 108, 141, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpwd_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwd_PasswordKeyPressed
        if(evt.getKeyCode()==10)
        {
            //controlador.buscar();
        }
    }//GEN-LAST:event_jpwd_PasswordKeyPressed

    private void jb_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_LoginActionPerformed

    private void jpwd_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwd_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwd_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
   
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb_Login;
    private javax.swing.JLabel jl_Bienvenido;
    private javax.swing.JLabel jl_contrasena;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JPasswordField jpwd_Password;
    private javax.swing.JTextField jt_usuario;
    // End of variables declaration//GEN-END:variables
}
