
package Vista;

import Controlador.Controlador_FRM_MantenimientoUsuarios;


public class GUI_InformacionUsuarios extends javax.swing.JPanel {

    Controlador_FRM_MantenimientoUsuarios controlador;
    public GUI_InformacionUsuarios() {
        initComponents();
    }
    
    public void agregarEventos(Controlador_FRM_MantenimientoUsuarios controlador){
        this.controlador=controlador;
    }
    
    public String[] devolverInformacion(){
        String arreglo[];
        arreglo= new String[4];
        arreglo[0]=this.jl_IDUsuario.getText();
        arreglo[1]=this.jl_Password.getText();
        arreglo[2]=this.jl_Nombre.getText();
        arreglo[3]=this.jl_Apellidos.getText();
        return arreglo;
    }
    
    public String devolverIDUsuario(){
        return this.jl_IDUsuario.getText();
    }
    public String devolverPassword(){
        return this.jl_Password.getText();
    }
    public String devolverNombre(){
        return this.jl_Nombre.getText();
    }
    public String devolverApellidos(){
        return this.jl_Apellidos.getText();
    }
    public void mostrarInformacion(String[] arreglo){
        this.jl_Password.setText(arreglo[0]);
        this.jl_Nombre.setText(arreglo[1]);
        this.jl_Apellidos.setText(arreglo[2]);
    }
    public void limpiar(){
        this.jl_IDUsuario.setText("");
        this.jl_Password.setText("");
        this.jl_Nombre.setText("");
        this.jl_Apellidos.setText("");
    }
    public void estadoInicial(){
        this.jl_IDUsuario.setEnabled(true);
        this.jl_Password.setEnabled(false);
        this.jl_Nombre.setEnabled(false);
        this.jl_Apellidos.setEnabled(false);
    }
    public void deshabilitarIDUsuario(){
        this.jl_IDUsuario.setEnabled(false);
    }
    public void habilitarOpciones(){
        this.jl_IDUsuario.setEnabled(false);
        this.jl_Password.setEnabled(true);
        this.jl_Nombre.setEnabled(true);
        this.jl_Apellidos.setEnabled(true);
    }
    public void habilitarAgregar(){
        this.jl_IDUsuario.setEnabled(true);
        this.jl_Password.setEnabled(true);
        this.jl_Nombre.setEnabled(true);
        this.jl_Apellidos.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jl_Password = new javax.swing.JPasswordField();
        jl_IDUsuario = new javax.swing.JTextField();
        jl_Nombre = new javax.swing.JTextField();
        jl_Apellidos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre de usuario:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setText("Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setText("Nombre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setText("Apellidos:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        add(jl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, -1));

        jl_IDUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_IDUsuarioKeyPressed(evt);
            }
        });
        add(jl_IDUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 210, -1));
        add(jl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 210, -1));
        add(jl_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jl_IDUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_IDUsuarioKeyPressed
       if(evt.getKeyCode()==10){
            if(this.controlador.archivoElegido==1){
            controlador.buscarEnArchivosPlanos();
        }else
        if(this.controlador.archivoElegido==2){
            controlador.buscarBD();
        }else
        if(this.controlador.archivoElegido==3){
            controlador.buscarXML();
        }
      }
    }//GEN-LAST:event_jl_IDUsuarioKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jl_Apellidos;
    private javax.swing.JTextField jl_IDUsuario;
    private javax.swing.JTextField jl_Nombre;
    private javax.swing.JPasswordField jl_Password;
    // End of variables declaration//GEN-END:variables
}
