
package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;

public class GUI_InformacionCursos extends javax.swing.JPanel {
    
    Controlador_FRM_MantenimientoCursos controlador;
    
    public GUI_InformacionCursos() {
        initComponents();
        cargarCreditos();
    }
    public void cargarCreditos(){
        this.jcb_Creditos.removeAllItems();
        for(int contador=0;contador<10;contador++){
        this.jcb_Creditos.addItem(""+contador);
        }
        this.jcb_Creditos.setSelectedIndex(4);
    }
    public void agregarEventos(Controlador_FRM_MantenimientoCursos controlador){
        this.controlador=controlador;
    }
    public String[] devolverInformacion(){
        String arreglo[];
        arreglo =new String[4];
        arreglo[0]=this.jt_NombreDelCurso.getText();
        arreglo[1]=this.jt_Siglas.getText();
        arreglo[2]=""+this.jcb_Creditos.getSelectedIndex();
        arreglo[3]=this.jt_Horario.getText();
        return arreglo;
    }
    
    public String devolverSigla()
    {
        return this.jt_Siglas.getText();
    }
   public String devolverNombre()
    {
        return this.jt_NombreDelCurso.getText();
    }
   public String devolverCreditos()
    {
        return ""+this.jcb_Creditos.getSelectedItem();
    }
   public String devolverHorario(){
       return this.jt_Horario.getText();
   }
    public void mostrarInformacion(String[] arreglo){
        this.jt_NombreDelCurso.setText(arreglo[0]);
        this.jcb_Creditos.setSelectedItem(arreglo[1]);
        this.jt_Horario.setText(arreglo[2]);
    }
    public void limpiar()
    {
        this.jt_Siglas.setText("");
        this.jt_NombreDelCurso.setText("");
        this.jt_Horario.setText("");
    }
    public void estadoInicial(){
        this.jt_Siglas.setEnabled(true);
        this.jt_NombreDelCurso.setEnabled(false);
        this.jcb_Creditos.setEnabled(false);
        this.jt_Horario.setEnabled(false);
    }
    public void deshabilitarSigla(){
        this.jt_Siglas.setEnabled(false);
    }
    public void habilitarOpciones(){
        this.jt_Siglas.setEnabled(false);
        this.jt_NombreDelCurso.setEnabled(true);
        this.jcb_Creditos.setEnabled(true);
        this.jt_Horario.setEnabled(true);
    }
    public void habilitarAgregar(){
        this.jt_Siglas.setEnabled(true);
        this.jt_NombreDelCurso.setEnabled(true);
        this.jcb_Creditos.setEnabled(true);
        this.jt_Horario.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_NombreDelCurso = new javax.swing.JTextField();
        jt_Siglas = new javax.swing.JTextField();
        jcb_Creditos = new javax.swing.JComboBox();
        jl_Horario = new javax.swing.JLabel();
        jt_Horario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre del Curso: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("Siglas: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setText("Creditos: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        add(jt_NombreDelCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 270, -1));

        jt_Siglas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_SiglasKeyPressed(evt);
            }
        });
        add(jt_Siglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 270, -1));

        jcb_Creditos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jcb_Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jl_Horario.setText("Horario");
        add(jl_Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        add(jt_Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jt_SiglasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_SiglasKeyPressed
        if(evt.getKeyCode()==10){
            controlador.buscar();
        }
    }//GEN-LAST:event_jt_SiglasKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jcb_Creditos;
    private javax.swing.JLabel jl_Horario;
    private javax.swing.JTextField jt_Horario;
    private javax.swing.JTextField jt_NombreDelCurso;
    private javax.swing.JTextField jt_Siglas;
    // End of variables declaration//GEN-END:variables
}
