
package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;


public class GUI_InformacionEstudiantes extends javax.swing.JPanel {
    
    Controlador_FRM_MantenimientoEstudiantes controlador;
    
    public GUI_InformacionEstudiantes() {
        initComponents();
    }
    public void agregarEventos(Controlador_FRM_MantenimientoEstudiantes controlador)
    {
        this.controlador=controlador;
    }
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo =new String[3];
        arreglo[0]=this.jt_Cedula.getText();
        arreglo[1]=this.jt_NombreCompleto.getText();
        arreglo[2]=this.jt_Direccion.getText();
        return arreglo;
    }
    
    public String devolverCedula(){
        //System.out.println("aqui tambien");
        return this.jt_Cedula.getText();
    }
    public String devolverNombre(){
        return this.jt_NombreCompleto.getText();
    }
    public String devolverDireccion(){
        return this.jt_Direccion.getText();
    }
    public void mostrarInformacion(String[] arreglo){
        this.jt_NombreCompleto.setText(arreglo[0]);
        this.jt_Direccion.setText(arreglo[1]);
    }
    public void limpiar()
    {
        this.jt_Cedula.setText("");
        this.jt_NombreCompleto.setText("");
        this.jt_Direccion.setText("");
    }
    public void estadoInicial(){
        this.jt_Cedula.setEnabled(true);
        this.jt_NombreCompleto.setEnabled(false);
        this.jt_Direccion.setEnabled(false);
    }
    public void deshabilitarCedula(){
        this.jt_Cedula.setEnabled(false);
    }
        
    public void habilitarOpciones(){
        this.jt_Cedula.setEnabled(false);
        this.jt_NombreCompleto.setEnabled(true);
        this.jt_Direccion.setEnabled(true);
    }
    public void habilitarAgregar(){
        this.jt_Cedula.setEnabled(true);
        this.jt_NombreCompleto.setEnabled(true);
        this.jt_Direccion.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreCompleto = new javax.swing.JTextField();
        jt_Direccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cedula:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nombre completo: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jt_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_CedulaKeyPressed(evt);
            }
        });
        add(jt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, -1));
        add(jt_NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, -1));
        add(jt_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 240, -1));

        jLabel3.setText("Direccion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_CedulaKeyPressed
       if(evt.getKeyCode()==10){
            if(this.controlador.archivoElegido==1){
            controlador.buscarEnArchivosPlanos();
        }else
        if(this.controlador.archivoElegido==2){
            controlador.buscarBD();
        }else
        if(this.controlador.archivoElegido==3){
            controlador.buscarXML();
        }
      }
    }//GEN-LAST:event_jt_CedulaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_NombreCompleto;
    // End of variables declaration//GEN-END:variables
}
